### ISSUE TITLE
Multi-thread jobs & streaming improvements

### ISSUE THREAD

**Issue by eligrey** [transcend-io/penumbra#106]
Penumbra should offer an option to use multiple job execution threads/workers for improved performance.

This will require a major refactor touching streaming, error handling, and a new job API model. Fixing this could unburden much of penumbra's tech debt.

- [x] Use an adaptive worker pool
- [x] Improve job API model

**Comment by hannahhenderson** [comment]
Standup update:
- Eli's planning to pick this up today-ish

**Comment by hannahhenderson** [comment]
Standup:

Lots of reading up on MDN, this is worker-heavy code.

**Comment by hannahhenderson** [comment]
Standup update:
- Ben or Mike will likely need to review this. Should we be getting other people up to speed in Penumbra?
- How do we normally maintain Penumbra?
  - We don't... or rather, we do in fits and spurts around Airgap
- How do we monitor when it needs fixes?
  - Right now, when it's used at a conference
- Do we keep an eye on the Issues in GH?
  - We're presenting it at SOUPS tomorrow... so issue count may increase
- By making it open source we've implicitly stated that we're going to support it
  - Preference: Keep GH as the source of all interaction
  - Unless we're able to support real-time responses, we should not be opening up other avenues of communication
