### ISSUE TITLE
Question: What's missing on Safari?

### ISSUE THREAD

**Issue by cristianocca** [transcend-io/penumbra#107]
Just wondering, are there plans to support `encrypt` on Safari? What's missing about it?

Also, what's the role of `authTag`? Which algorithms are used for encryption/decryption?  It would be great to have some docs about all that. Given the lack of encryption support on Safari, I was thinking about encrypting server side (e.g., with AES CTR + IV + Key derived from PBKDF2), but I can't seem to find a way to decrypt a file encrypted like that.

**Comment by michaelfarrell76** [comment]
@eligrey could you add some context here?

**Comment by eligrey** [comment]
Safari has some bugginess with encryption streaming that may eventually get fixed with a workaround or whenever Safari gets support for the `TransformStream` constructor.

**Comment by bencmbrook** [comment]
Hey @cristianocca, currently this lib is built to support AES 256 in GCM mode. We’ll likely expand the algorithm set in the near future, but CTR mode is not yet supported. Since GCM is authenticated encryption, authTag is the cryptographic checksum used to validate that data is authentic (has not been altered). It’s created after encrypting a piece of data, and is required to decrypt that data at a later time. More here https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf

If your server is Node, check out the crypto library’s cipher.getAuthTag() method

**Comment by cristianocca** [comment]
Hello,

Thanks for the responses, that's really helpful! It would be great to have this info on the docs as well (I'm sorry if it's there already).

Our backend is in Python so GCM may be tricky. However, we are still just researching so who knows safari might be working by then.

**Comment by bencmbrook** [comment]
@cristianocca - of course! Really curious to hear about your use case! Would you mind sharing what you're building?

AES in GCM [can be done in Python with this](https://cryptography.io/en/latest/hazmat/primitives/aead/#cryptography.hazmat.primitives.ciphers.aead.AESGCM.encrypt). Note this lib appends the authTag to the output ciphertext so you'll have to split off the last 16 bytes to get your authTag.

**Comment by cristianocca** [comment]
A feature of a website we are building implements a "secure file sharing" process. Although we allow for PDF/Docx encryption (which is weak), and access is strictly provided to authenticated users, we want to add another extra layer of protection. This new layer would be full file encryption, but we don't want to know the keys or encrypt it on the server, so it would need to be 100% client side.  This would include key derivation with PBKDF2 from user input, and AES encryption (in any acceptable variant) of the file. This way, the server and storage would never be able to see the file's content, and if the download short-lived signed URL is leaked, the file would still remain secure and only accessible to the owner of the key :)

**Comment by bencmbrook** [comment]
That is awesome. That's a perfect use case for this library, especially given file sizes can be arbitrarily large.

I've broken this into two issues (#108 and #109) and will close this out in favor of those.

Let us know if you have any other issues as you work with the lib!

**Comment by cristianocca** [comment]
Thanks for the detailed answers!

One last question. What happens to Chrome in MacOS? Does it work or does it have the same issues as Safari? I'm asking this since Chrome uses webkit on macOS/iOS (if I'm not wrong), so Chrome is really just a disguised Safari on those platforms.

**Comment by bencmbrook** [comment]
MacOS Chromes use Blink, but iOS Chromes still use webkit. I don't believe this has been tested in the iOS Chrome App yet - but I imagine the Safari issue would apply there.
