### ISSUE TITLE
Support Firefox & Safari for .encrypt & .saveZip

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#108]
Conflux [uses a ponyfill](https://github.com/transcend-io/conflux/blob/5e53d10c7e44ab3db7d4b3ef8738ebc1e7436b85/src/write.js#L10) for Safari transform streams. Is this an applicable solution for Penumbra `.encrypt`?

**Comment by eligrey** [comment]
That may possibly help. I can spend some time next week experimenting with and evaluating our `TransformStream` workaround options.

**Comment by bencmbrook** [comment]
Note: we may want to change Conflux to not overwrite the `TransformStream` variable, e.g.

```
import ponyfill from 'web-streams-polyfill/ponyfill';
const TransformStream = window.TransformStream || ponyfill.TransformStream
```

**Comment by bencmbrook** [comment]
Confirmed Conflux is running on Safari, FF, Chrome, Edge now!
