### ISSUE TITLE
compare vs openpgpjs

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#127]
https://github.com/openpgpjs/openpgpjs#browser

looks like you can use threads and streams?

**Comment by eligrey** [comment]
It looks like openpgpjs might have everything we need: https://github.com/openpgpjs/openpgpjs/pull/430

We should do a benchmark of their threaded solution & also determine if it supports batch splitting over multiple worker threads (which we could conceivably do soon in Penumbra)

**Comment by bencmbrook** [comment]
Looks like it only streams with unauthenticated encryption and a draft spec where every chunk is authenticated.. makes sense, WebCrypto doesn't support streaming, so it needs to check auth on every `decrypt` call (each chunk) or not at all.
