### ISSUE TITLE
Save to IndexedDB ("prefetch")

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#130]
Can we write decrypted streams to IndexedDB? This can be a nice way of implementing "prefetch". Files that aren't yet needed can be fetched, decrypted, put into IndexedDB, then pulled out when needed (e.g. when arriving at that page).

**Comment by eligrey** [comment]
This is possible but it would massively eat into the client side storage limits. It's much more advisable for us to use the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) for manual response caching.

We can cache client-side decrypted files with a ServiceWorker in combination with the Cache API

**Comment by bencmbrook** [comment]
Good point! Will close this out then
