### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by coreyward** [transcend-io/penumbra#152]
I think there's something wrong with the build or the instructions (maybe a dependency?). I tried to use this, but no matter what I tried I got the above error. Even just doing `import { penumbra } from '@transcend-io/penumbra';` in a webpack/React app or adding the pre-built `build/penumbra.js` to an HTML page a results in the error.

**Comment by eligrey** [comment]
What browser(s) are you getting this error on?

**Comment by coreyward** [comment]
Chrome 85.0.4183.121.

In Firefox 80.0.1 and 81.0.1, a quick `appendChild` results in `TypeError: o.push is undefined`.

Safari 14.0 similarly complains: `TypeError: undefined is not an object (evaluating 'o.push.bind')`

**Comment by coreyward** [comment]
Hmm, actually, I'm able to get it to work fine if I just use the pre-built file in a plain HTML file that isn't being touched by Webpack. I suspect there's something unconventional happening with the way this library uses Webpack. Unfortunately I'm using a framework that doesn't provide any mechanisms for manipulating the webpack configuration: https://github.com/sanity-io/sanity

**Comment by michaelfarrell76** [comment]
is there any way for you to just copy in the penumbra files post webpack build? it's really as simple as that

our webpack plugin looks like:

```js
  plugins: [
    // Copy in penumbra workers
    new CopyPlugin({
      patterns: [
        {
          from: `${PENUMBRA_DIRECTORY}/penumbra.worker.js`,
          to: `${outputPath}/penumbra.worker.js`,
        },
        {
          from: `${PENUMBRA_DIRECTORY}/penumbra.js`,
          to: `${outputPath}/penumbra.js`,
        },
      ],
    }),
```

where `PENUMBRA_DIRECTORY` is absolute path to the node_modules build
```
/**
 * Path to penumbra build
 */
module.exports.PENUMBRA_DIRECTORY = join(
  __dirname,
  'node_modules',
  '@transcend-io/penumbra',
  'build',
);
```
and `outputPath` is the compiled build.

**Comment by coreyward** [comment]
@michaelfarrell76 I would need to have a separate Webpack configuration to do anything, and I'm doubtful that would work in a plugin like I'm trying to build. For context, today there is no way to securely upload files to the Sanity.io service via the open source Studio CMS. I'm working on a plugin for the Studio that that will encrypt files prior to upload (access to the uploaded assets is public) and store the generated key in the Studio dataset (access to which is authenticated). As a result, I'm fairly constrained in terms of the configuration. 

I'm spiking on doing this in an iframe and using `postMessage` to send the file back up to the parent frame for upload, but it's not ideal— Penumbra will be loaded for each iframe on the page individually, and there's the additional potential for exposure of the generated key through a misconfigured origin (again, this is a plugin, so I won't have any access to the origin hostname in a production setting).

**Comment by michaelfarrell76** [comment]
let us know if you find out anything more! a bit tricky for us to help without having control over the webpack compilation but happy to address any questions you may have

**Comment by coreyward** [comment]
I haven't run into this before, so I'm kind of unsure why any Webpack configuration is required. Is there something in particular that Penumbra does that means it isn't possible to build it in a way that it can be imported and used like any other package? The statically built library contains references to webpack that conflict which isn't something I would expect.

**Comment by eligrey** [comment]
@coreyward The reason that importing penumbra is a little more involved than other packages is because we include a required web worker module.

This web worker module is not currently inlined into our entry bundle. It should be possible to inline the web worker module so that it can be loaded from a Blob URI generated at runtime from minified JS source.

I've filed an issue for this feature: https://github.com/transcend-io/penumbra/issues/153

**Comment by coreyward** [comment]
@Eli Thanks for the context! That sounds like a great improvement. Any idea what sort of rough ETA we might be looking at for something like that?

**Comment by eligrey** [comment]
@coreyward Also your specific error appears to be related to `window.webpackJsonp` being a truthy non-array value in your environment.

I noticed this in our generated code from Webpack:

<img width="611" alt="Screen Shot 2020-10-13 at 3 51 15 PM" src="https://user-images.githubusercontent.com/46995/95924232-0ebf9e00-0d6c-11eb-8ec3-11de7750b58c.png">

As for an ETA for inlining the penumbra worker script, I can't give any hard figures at this time as it is not my current priority. Once I start working on it, it will probably take less than a week to get finished.

**Comment by coreyward** [comment]
Ohhh yeah it looks like Sanity is still using Webpack 3, where `window.webpackJsonp` was a function. @kmelve Are you aware of any efforts at Sanity to update to Webpack 4+?

**Comment by kmelve** [comment]
Yes! We're actually starting that work now, and I believe we're going right to 5.

**Comment by michaelfarrell76** [comment]
hey @coreyward @kmelve is this still an issue for you all?
