### ISSUE TITLE
Configurable streamsaver endpoint

### ISSUE THREAD

**Issue by eligrey** [transcend-io/penumbra#161]
Penumbra should have an option for configuring the streamsaver HTML endpoint. This should improve security by allowing library users to self-host the endpoint instead of having to rely on our hardcoded endpoint.

**Comment by dmattia** [comment]
Removed the security label as this seems more like a nice-to-have than an actual security vulnerability. Feel free to re-label, assign a priority, and assign someone if you believe this is a mistake @eligrey

**Comment by eligrey** [comment]
@dmattia Sure, makes sense. I went ahead and created a security-nice label for issues like these.

**Comment by dougiefresh49** [comment]
@eligrey is there any update on this or do you know where i could add the configuration in? Happy to help / contribute a pr.

**Comment by eligrey** [comment]
@dougiefresh49 You'll be able to configure the streamsaver endpoint through `data-streamsaver-endpoint="[url]"` on the penumbra script tag once #213 merges.
