### ISSUE TITLE
Offload decryption to Worker

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#17]
Fetching, decrypting, zipping, and saving will start to get really slow when we start incorporating large files. 

This is because (A) Safari doesn't support WriteStreams and (B) JSZip reads files into a Blob (i.e. fully into memory) rather than a stream. 

I'm working on a streaming zip alternative based on [this issue](https://github.com/eligrey/FileSaver.js/issues/558) (~which might encourage the community to build a library~ we're [building an open source package](https://github.com/transcend-io/conflux) with Jimmy Warting). I'm also working on bundling a service worker option into Penumbra, but it should be done on privacy-page so the .zip bundling is done on the SW as well.

While these are good speedups, a simpler solution is to offload this processing to a Service Worker so it doesn't block the DOM thread. 

The service worker should do everything until the final output - so it fetches, decrypts, zips, and then sends the final output to the DOM thread for use (often a stream of data - e.g. the final zip - or otherwise an output, like a string of decrypted text, or the `src` of an object URI for media).

This was done successfully with Penumbra here using [Comlink](https://github.com/GoogleChromeLabs/comlink):

- https://github.com/transcend-io/penumbra/blob/c9a5febadafb07120731cc4d97eb04cf23032b05/example/decryption.worker.js#L1-L20
- https://github.com/transcend-io/penumbra/blob/c9a5febadafb07120731cc4d97eb04cf23032b05/example/example.js#L19-L23
- https://github.com/transcend-io/penumbra/blob/c9a5febadafb07120731cc4d97eb04cf23032b05/example/example.js#L61-L63
- https://github.com/transcend-io/penumbra/blob/c9a5febadafb07120731cc4d97eb04cf23032b05/example/webpack.config.js#L21-L25

**Comment by eligrey** [comment]
Using `Transferable`s alone (via Comlink) should be enough for our use cases. We won't have to use SharedArrayBuffer + Atomics.

I'm going to start expanding on the Comlink integration to see how close I can get the API to #42. My initial prototypes will use JSZip as conflux is still in development.

**Comment by eligrey** [comment]
Since neither the zip or decryption workers need to be on a ServiceWorker, it seems best to create them dynamically using blob URLs. This will make using Penumbra easier in terms of configuration and distribution (one main thread file + one ServiceWorker file).
