### ISSUE TITLE
Encryption example

### ISSUE THREAD

**Issue by teja42** [transcend-io/penumbra#194]
I see that there are lots of examples for decryption but there isn't a good example for encryption. The documentation for the encrypt function is also not great. An example for encrypt function or detailed documentation for encrypt function would be great.

**Comment by rogangs2** [comment]
Yeah, I agree with @teja42. It will be more helpful if there are encryption samples and documentation.

**Comment by michaelfarrell76** [comment]
hey @teja42 @rogangs2 sorry for the delay here, but we're adding some examples here: https://github.com/transcend-io/penumbra/pull/196/files

let us know if these are helpful!

**Comment by eligrey** [comment]
API docs for penumbra.encrypt() including examples are here: https://github.com/transcend-io/penumbra#encrypt

I'm closing this issue for now. Please feel free to reach out if you'd like some more assistance in using Penumbra!
