### ISSUE TITLE
Penumbra is getting high cpu usage even when not encrypting or decrypting

### ISSUE THREAD

**Issue by yaronvhop** [transcend-io/penumbra#214]
Can be reproduced with a very small code on chrome 99: 

```index.js
// This is all of the Penumbra-relevant code:
const onReady = async (
  { detail: { penumbra } } = {
    detail: self,
  },
) => {
  penumbra.setWorkerLocation('/worker.penumbra.js');
};

if (!self.penumbra) {
  self.addEventListener('penumbra-ready', onReady);
} else {
  onReady();
}

```

```index.html
<HTML>
<HEAD></HEAD>
<Body>
    <script src="main.penumbra.js" async defer></script>
    <script src="index.js"></script>
</Body>
</HTML>
```

Usually it uses high CPU for ~1min, but sometimes I see it going over an hour!

![image](https://user-images.githubusercontent.com/76743257/158023590-19a879d4-3440-42ed-b898-5d7029b24160.png)

On FF does not seem to happen at all. 

When profiling on Chrome, all I can see is a bunch of empty "Task" in the flame chart, without any JS code. 

Any idea?

Thanks!

**Comment by eligrey** [comment]
Interesting. I will definitely look into this next week, as we shouldn't be doing anything in the background without jobs running.

If I had to guess, it could potentially be misreported usage due to idle worker overhead.

**Comment by yaronvhop** [comment]
Hey,
I see the high CPU in Windows Task manager as well 

![image](https://user-images.githubusercontent.com/76743257/158034456-c1b2ccce-d447-4c99-a4c9-2543447dbd1d.png)

In my PC 3 percent is a full core (32 threads CPU), it seems the numbers do match Chrome Task Manager, both in CPU % and in CPU time.

Thanks!

**Comment by yaronvhop** [comment]
A screenshot from the profiler, a very weird empty tasks

![image](https://user-images.githubusercontent.com/76743257/158038118-51c3ed62-3177-43d9-86e4-2f32690e33ad.png)

Seems to be some internal chrome issue. I am 100% clueless
Hope you will have a better idea
Thanks again!

**Comment by eligrey** [comment]
This issue seems to be gone in Chrome 103 with [Penumbra 6.0](https://github.com/transcend-io/penumbra/pull/229)
