### ISSUE TITLE
import { penumbra } from "@transcend-io/penumbra" does not work on vite

### ISSUE THREAD

**Issue by akriafly** [transcend-io/penumbra#215]
I tried to import penumbra by 
`import { penumbra } from "@transcend-io/penumbra"`

vite:import-analysis throw 
`
 [vite] Internal server error: Failed to resolve entry for package "@transcend-io/penumbra". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@transcend-io/penumbra". The package may have incorrect main/module/exports specified in its package.json.
`

How do I fix this error?

**Comment by bencmbrook** [comment]
Apologies @akriafly - it looks like there was an issue with the build output of the version you're on. Upgrading to 5.3.0 should fix!
