### ISSUE TITLE
Future of downloadEncryptedFile and getDecryptedContent

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#23]
Right now Penumbra bundles StreamSaver.js and implements a download function and a display function.

Should Penumbra be just about returning a ReadableStream of deciphered data? After all, these ReadableStreams are what we'd want to use as input to [conflux](https://github.com/transcend-io/conflux)..

`fetchAndDecipher` is the bread and butter of Penumbra. The repo description is "Fetch and decrypt files in the browser" - that's this function.

`downloadEncryptedFile` and `getDecryptedContent` (and their helpers) are just use cases that extend `fetchAndDecipher` to download the file or display it in the DOM 

Perhaps we break out these specific use-cases into another file?

**Comment by eligrey** [comment]
I feel like the current state of the exported API is fine for my liking. Should we close this?
