### ISSUE TITLE
Penumbra 3.0 API

### ISSUE THREAD

**Issue by bencmbrook** [transcend-io/penumbra#42]
The new API will incorporate [file zipping](https://github.com/transcend-io/conflux) and [saving](https://github.com/jimmywarting/StreamSaver.js) now, since we’re building everything to be streamable and all performed inside a Service Worker.

Maybe it's a chainable thing?
```js
fetchManyAndDecrypt(resources).save()
fetchManyAndDecrypt(resources).getTextOrURI()
fetchAndDecrypt(resource).save()
fetchAndDecrypt(resource).getTextOrURI()
```

@giacaglia @eligrey

**Comment by michaelfarrell76** [comment]
Looks cool, probably a third method that would return the regular blob too yeah?

**Comment by eligrey** [comment]
I concur with @michaelfarrell76.

Here's my envisioned API:

```js
await fetchManyAndDecrypt(resources: RemoteResource[]).save(overrideFilename:string, compress:boolean=false)
await fetchManyAndDecrypt(resources).getTextOrURI(encoding:string='UTF-8')
await fetchManyAndDecrypt(resources).getBlob(encoding:string='UTF-8')
await fetchManyAndDecrypt(resources).getTextOrURI(...)
await fetchAndDecrypt(resource).save(...)
await fetchAndDecrypt(resource).getTextOrURI(...)
await fetchAndDecrypt(resources).getBlob(...)
```

**Comment by giacaglia** [comment]
Is there a difference between fetchManyAndDecrypt(resource]) and fetchAndDecrypt(resource)? Should it be two different methods? Having just one `fetchManyAndDecrypt` might simplify the API

Also `getTextOrURI` would return a string, should we include in the response if it is a URI or not? 

@eligrey What would be the difference of `getBlob` and `getTextOrURI`

**Comment by eligrey** [comment]
@giacaglia The main difference would be that `.save()` on `fetchManyAndDecrypt` would save a ZIP and saves just the individual file on `fetchAndDecrypt`.

**Comment by michaelfarrell76** [comment]
I think he was saying how can you differentiate it it the return value is the image uri or the result in plain text? Could be left to the implementor using the provided mimetypes but not sure

**Comment by eligrey** [comment]
`fetchManyAndDecrypt(resources).getTextOrURI()` could return `{text:string|null, uri:string|null}` and expect the implementor to check which one is not null, or  make it easier with `{type:'text'|'uri', text:string|null, uri:string|null}`

**Comment by giacaglia** [comment]
Yeah, either that or we can return a json with `type` and the `string` but that is not needed if we use the mimetype to differentiate

**Comment by michaelfarrell76** [comment]
Yeah either work for me. If it is Json I would prefer the text/data one but up to you as to whether we do object or string return type

**Comment by eligrey** [comment]
I don't think we want to merge together one `ServiceWorker` for StreamSaver + decryption + zipping. By implementing each of these features as separate worker threads, we get increased concurrency and don't block decryption on zipping & compression.

Here's my proposed thread layout for penumbra:

- DOM thread 1 (privacy center context)
  - Initializes and orchestrates the three worker threads and the streamsaver iframe. Most API calls go through comlink to the decryption worker.
- DOM thread 1 (Penumbra iframe context)
  - Handles writing streams to disk (cannot be done from a `Worker`)
- Decryption `Worker` + comlink
- Zip `Worker` + comlink
- `ServiceWorker` for StreamSaver only

Both DOM threads share one physical thread.

**Comment by bencmbrook** [comment]
> I concur with @michaelfarrell76.
> 
> Here's my envisioned API:
> 
> ```js
> await fetchManyAndDecrypt(resources: RemoteResource[]).save(overrideFilename:string, compress:boolean=false)
> await fetchManyAndDecrypt(resources).getTextOrURI(encoding:string='UTF-8')
> await fetchManyAndDecrypt(resources).getBlob(encoding:string='UTF-8')
> await fetchAndDecrypt(resource).save(...)
> await fetchAndDecrypt(resource).getTextOrURI(...)
> await fetchAndDecrypt(resources).getBlob(...)
> ```
> 
> `fetchManyAndDecrypt(resources).save(...)` would start saving a zip stream to disk containing all of the decrypted resources.

@eligrey we might consider matching the [Response methods](https://developer.mozilla.org/en-US/docs/Web/API/Response#Methods), or even return a Response object?

**Comment by eligrey** [comment]
@bencmbrook: If we can return `Response` objects, then I think `getBlob()` should be replaced with `getResponse()`. API consumers can then call `await response.blob()` to load the response as a blob.

**Comment by eligrey** [comment]
I'm making the 3.0 API hook into the Workers through Comlink. In the meantime, I'll continue to expose the 2.0 API, which will not use Workers.

The only core API method exported would be `await penumbra.get(...resources: RemoteResource[]): PenumbraFileList`

I think that Penumbra's 3.0 API should look like this:

    import penumbra from '@transcend-io/penumbra';
    const files: PenumbraFileList = await penumbra.get(resources);
    saveButton.addEventListener("click", () => {
        // saves a zip folder if files.length > 1
        await files.save();
    });
    await files[0].save(); // manually save a single file
    await files.getBlob(); // load entire zip
    await files.getTextOrURI(); // always returns a URI if zipped

`PenumbraFileList` and `compression` look like this:

	export enum compression {
	  store = 0,
	  low, medium, high
	}

    export type PenumbraFileList = {
        files: File[]; // files[i].name is used to store directory structure
        save: () => Promise<void>;
        getTextOrURI: () => Promise<string>;
        getBlob: () => Promise<Blob>;
        zip: (compressionLevel = compression.store: int) => Promise<ReadableStream>;
    };

`save()`, `getTextOrURI()`, and `getBlob()` all implicitly call `zip()` if `files.length` is greater than 1. To set a compression level, `zip` must be manually called.

**Comment by eligrey** [comment]
Also, for our initial implementation we will only support the `compression.store` compression level, and will throw an error for any other compression levels.

**Comment by michaelfarrell76** [comment]
cool looks great!

One note on the user of typescript enums. See #4 [here](https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680). People in general don't seem to like using typescript enums because of the confusing nature as to whether they are runtime accessible or not.

In general i have tried to to follow the paradigm:

1. Use string literal type when possible: i.e. type Compression = 'low' | 'medium' | 'high'
2. If you need to use an enum, use strings as values:

```
export enum compression {
  Store = 'STORE',
  Low = 'LOW',
  Medium = 'MEDIUM',
  High = 'HIGH'
}
```

I am actually writing up a style guide now that hopefully clarifies things like this.

**Comment by bencmbrook** [comment]
Love that API
