### ISSUE TITLE
Standardize a way to declare worker script locations

### ISSUE THREAD

**Issue by eligrey** [transcend-io/penumbra#46]
We should standardize a way to declare worker script locations. We will have three worker scripts: one for decryption (implementing penumbra methods), one for zipping (through conflux), and one for streamsaver.

We have a few possible options:

1. Require that `./penumbra-decrypt.worker.js` and `./penumbra-zip.worker.js` are present wherever Penumbra is used. (we're going to do this by default if no configuration is set)
2. Allow Penumbra consumers to configure worker script locations through Penumbra API (e.g. `Penumbra.setWorkerLocation('/worker-scripts/')`)
3. Allow configuration through script element (e.g. `<script src="penumbra.js" data-worker-dir="/worker-scripts/"/>` or maybe `<script src="penumbra.js" data-workers='{"decrypt":"https://example.com/decryption.worker.js","zip":"/worker-scripts/zip.worker.js"}"/>`)
4. Hardcode decryption and zipping worker locations and host them ourselves.
5. Allow configuration through `<link rel="penumbra" data-config="...">` (placed before the Penumbra script element)

**Comment by michaelfarrell76** [comment]
1-3 sound good to me

**Comment by eligrey** [comment]
I decided on 1-3, implemented as `penumbra.setWorkerLocation({dir?:URL|string, decrypt?:URL|string, zip?:URL|string})`, which is also auto-called using `JSON.parse(document.currentScript.dataset.workers)`.

**Comment by eligrey** [comment]
Closed by #54
