### ISSUE TITLE
Firefox does not work -- need to increase coverage

### ISSUE THREAD

**Issue by michaelfarrell76** [transcend-io/penumbra#92]
<img width="635" alt="Screen Shot 2019-12-10 at 11 40 15 AM" src="https://user-images.githubusercontent.com/10264973/70562744-d8106a00-1b41-11ea-8b74-528a29f817d1.png">

@eligrey could you please run some tests on the dev or prod environment to verify that penumbra is working in the following browsers:

- [ ] safari
- [ ] firefox
- [ ] brave

would also be great to have some tests back online for this.

**Comment by eligrey** [comment]
We currently end up duplicating every file twice on browsers that don't support native write streams by buffering and by passing them in and out of worker threads.

I'm going to address this by using a non-worker solution for these browsers, which should halve the memory usage and decrease crashes for small files.

**Comment by eligrey** [comment]
Merging into #108
